datasources.default.db-type=postgres
datasources.default.driver-class-name=org.postgresql.Driver
flyway.datasources.default.enabled=true

r2dbc.datasources.default.db-type=postgres
r2dbc.datasources.default.dialect=POSTGRES

micronaut.application.name=coprogo
micronaut.environments.default=runtime,local
micronaut.security.authentication=bearer
micronaut.security.token.jwt.signatures.jwks.google.url=${coprogo.security.google-id-token.jwks-url}

coprogo.security.google-id-token.audiences=${GOOGLE_ID_TOKEN_AUDIENCES}
coprogo.security.google-id-token.issuers=accounts.google.com,https://accounts.google.com
coprogo.security.google-id-token.jwks-url=https://www.googleapis.com/oauth2/v3/certs

# OpenAPI generation and local exposure
micronaut.router.static-resources.swagger.paths=classpath:META-INF/swagger
micronaut.router.static-resources.swagger.mapping=/swagger/**
