datasources.migration.url=jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
datasources.migration.username=${app.database.username}
datasources.migration.password=${app.database.password}

r2dbc.datasources.default.url=r2dbc:pool:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
r2dbc.datasources.default.username=${app.database.username}
r2dbc.datasources.default.password=${app.database.password}
