package tech.justdev.pitest

import org.pitest.mutationtest.build.InterceptorParameters
import org.pitest.mutationtest.build.MutationInterceptor
import org.pitest.mutationtest.build.MutationInterceptorFactory
import org.pitest.plugin.Feature

class CoprogoEquivalentKotlinMutationFilterFactory : MutationInterceptorFactory {
    override fun description(): String = "Filters verified equivalent mutations generated by Kotlin inline collection functions"

    override fun createInterceptor(parameters: InterceptorParameters): MutationInterceptor =
        CoprogoEquivalentKotlinMutationFilter(EquivalentMutationWhitelist.load())

    override fun provides(): Feature =
        Feature
            .named("FCOPROGO_KOTLIN_EQUIVALENT")
            .withDescription(description())
            .withOnByDefault(true)
}
